### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ksajdu** [Jinzhong-Duan/reasoning-rcnn#1]
Can you provide more details? Thank you very much!

**Comment by JinZhongDUAN** [comment]
I seem to be having some problems again, and I'm trying to work them out.

**Comment by ksajdu** [comment]
We look forward to your improvement. The original author did not provide the version of the source code MMdetection and the version of the third-party library. It's really hard to start.

**Comment by JinZhongDUAN** [comment]
> 

The project has been updated and is ready to run
